### PR TITLE
Update install.sh python3-pymodbus

### PR DESCRIPTION
**Pull request by borpin**
Add python3-pymodbus required for TCP interfacer.

### CODE REVIEW

**Comment by alexandrecuer** [comment]
are yu sure ?
I am using the modbus interfacer heavily and I do : 
```
pip3 install -U pymodbus
```
cf https://github.com/riptideio/pymodbus#installing

**Comment by borpin** [comment]
General advice seems to be to use apt where possible as the version is tested with that distribution. pip should be used where the module is not available from apt - emon/OEM are not consistent on that.

In addition, past installs have been done with `sudo pip` which is again incorrect but difficult to fix going forward.

**Comment by alexandrecuer** [comment]
for pymodbus, I had in mind the module was not available via apt but 
maybe I am mistaking

best

Alex

**Comment by borpin** [comment]
```
pi@emonpi:~ $ apt-cache search python3-serial
python3-serial - pyserial - module encapsulating access for the serial port
```

**Comment by danbates2** [comment]
How about sticking **apt-get install rpi.gpio** in here too?

**Comment by borpin** [comment]
I used `python3-gpiozero` - which is better?

**Comment by borpin** [comment]
Actually, leave this alone and add to the Pulse Interfacer PR

**Comment by danbates2** [comment]
cool.

**Pull request merged**
