### PR TITLE
Enable RF TX sending via Jee Interfacer

### PR DESCRIPTION
**Pull request by alandpearson**
This opens the door to allowing emonhub to transmit to RF nodes using
for example MQTT

You need to add a 'TX' definition to emonhub.conf.
Below is an example for emonGLCD display

[[20]]
    nodename = emonglcd
    firmware =V1_1
    hardware = emonglcd
    [[[rx]]]
     names = temperature,
     datacodes = h
     scales = 0.01,1
     units = c
  [[[tx]]]
     names=nodeid,hour,minute,second,utilityW,solarW,utilityKwh,solarKwh
     datacodes =b,b,b,h,h,H,H
     units = h,min,sec,W,W,kwh,kwh

example MQTT publish payload that transmits to above node20:

emonhub/txi/20/14,38,34,700,138,2700,829

The corresponding struct in the emonglcd firmware :

typedef struct {
  byte nodeId ;
  byte hour, min, sec ;
  int utilityW, solarW, utilityKwh, solarKwh;
} PayloadTX;

.... and the corresponding code for data reception (again from emonglcd firmware)

// Did we receive any commands via RF ?
  if ( (rf12_recvDone() && rf12_crc == 0)  && ((rf12_hdr & RF12_HDR_CTL) == 0) ) {

    int node_id = (rf12_hdr & 0x1F);

      if (node_id == EMONTX && sizeof(emontx) == rf12_len ) {
        emontx = *(PayloadTX*) rf12_data; last_emontx = millis();
      }

  }

The datacodes are listed in the emonhub config documentation

This has been agressively tested on the lastest EMONPI releases and has
multiple MQTT publishers transmitting to multiple JeeNodes successfully.
It does not interfere with RF reception, nor require any changes to the
EMONPI firmware.
I have deliberately not used buffers, as TX can be time sensitive (for
example I use this to open & close JeeNode controlled window blinds via
nodeRed and Alexa)

This is very useful and makes emonhub/emonpi a great central JeeNode
communication station.

### CODE REVIEW

**Comment by glynhudson** [comment]
Awesome! Great addition :+1:

**Comment by alandpearson** [comment]
Wow, thanks Glyn

I think the doc isn't too clear and there is a typo (my fault).

The mqtt payload has an 'i' where there shouldn't be and I missed out 'values'

emonhub/tx**i**/20/14,38,34,700,138,2700,829

Correct is 
emonhub/tx/20/values/14,38,34,700,138,2700,829

And it's used to send, not what results from the send.

If you include this example using mosquitto_pub, it may help

```
mosquitto_pub -u 'emonpi' -P 'emonpimqtt2016' -t 'emonhub/tx/20/values' -m '14,38,34,700,138,2700,829'
```

That should clear it up :)

**Comment by glynhudson** [comment]
Thanks, I've just updated the docs. Please make a PR to the docs if you would like to make anymore changes: https://github.com/openenergymonitor/emonhub/commit/4fbc2891eb7696ac8e4ea3859a68b0ff5aa34d46

**Comment by Emmpunkt** [comment]
Found it by myself ;)
It depends on the datacodes. 
Negative consumption doesn´t work with `H`

**Comment by alandpearson** [comment]
Correct - H is unsigned (i.e positive integer only).    h is signed and allows negative values (I think to -327657).  
The data codes are described in the emonhub readme at the bottom of the conf page.

Sweet you got it working, glad I'm not the only one making use of Tx !

**Comment by Emmpunkt** [comment]
It was  a thing i never understood. Emoncms does all the calculations, but if you want to see it at the GLCD you have to do the calculations again on the GLCD.!? And everytime you unplug it, the data is lost?

I have EMONCMS for many years now (i think more then 10) and it is nice to see, that i can now show what ever i want...
I didn´t wrote a sketch now, but maybe in the next days.
Thank you and merry christmas

**Pull request merged**
