### PR TITLE
Modification of the EmonTCPModbusInterfacer to work with Pymodbus 1.4.0

### PR DESCRIPTION
**Pull request by alexandrecuer**
Tested on a Modbus TCP master SOFREL S500

### CODE REVIEW

**Comment by TrystanLea** [comment]
Thanks @alexandrecuer, what do you think would be the best way to catch the case where pymodbus is not installed? I got the following error when testing your changes:

    Traceback (most recent call last):
      File "src/emonhub.py", line 24, in <module>
        from interfacers import *
      File "/home/pi/emonhub/src/interfacers/EmonModbusTcpInterfacer.py", line 3, in <module>
        from pymodbus.constants import Endian
    ImportError: No module named pymodbus.constants

If I move the imports to within init, this avoids the error on systems where an EmonModbusTcpInterfacer configuration is not present, but it might be better to do a bit more error catching than this.. any suggestions welcome

    class EmonModbusTcpInterfacer(EmonHubInterfacer):

        def __init__(self, name, modbus_IP='192.168.1.10', modbus_port=0):
            """Initialize Interfacer
            com_port (string): path to COM port
            """

            from pymodbus.constants import Endian
            from pymodbus.payload import BinaryPayloadDecoder
            from pymodbus.client.sync import ModbusTcpClient as ModbusClient

**Comment by TrystanLea** [comment]
PS: thankyou for removing the lines:

    if I['Type'] in ('EmonModbusTcpInterfacer','EmonFroniusModbusTcpInterfacer') and not pymodbus_found
        self._log.error("Python module pymodbus not installed. unable to load modbus interfacer")

I missed these and have been trying to remove all module specific code from emonhub.py

**Comment by beaylott** [comment]
We could test this with a Victron battery system and will be in a position to test this soon with a SolarEdge inverter. Let me know if needed.

**Comment by alexandrecuer** [comment]
Indeed I see.... sorry in the rush I forgot the case pymodbus was not present 
Injection in the constructor as you propose is not working for me
I will try to find something working on both cases and come back to you

**Comment by alexandrecuer** [comment]
@TrystanLea : I've amended my pull request so that it is not producing anymore any error when pymodbus is not present...

**Comment by glynhudson** [comment]
@TrystanLea can this be merged now?

**Comment by glynhudson** [comment]
Thanks, very sorry too so long to merge 👍

**Pull request merged**
