### PR TITLE
Adding VEDirect interfacer and sample configuration

### PR DESCRIPTION
**Pull request by jlark**
Sending in PR for Victron product Integration.
**Notes**
- VE Direct is a binary protocol used by most Victron Energy products to communicate.
- Most VE Direct products connect through a  isolated FTDI - USB cable.

**Testing**
- This module has been tested on the BMV 700 which is a low cost battery monitoring unit.

**Configuration**
- Sample configuration has been added to the emonhub.conf file with comments

### CODE REVIEW

**Comment by glynhudson** [comment]
Thanks, this is great. Would it be possible to remove the commented out config from emonhub.conf and create a new file called something like vedirect.emonhub.conf containing the example config and maybe add to the readme or maybe better add a new file called vedirect.readme.md with a bit of info about what   vedirect is (I had not head of it before!), how it works and how to connect to emonhub. 

Do you have affiliation with victronenergy? Is this an open protocol they document or is is it a reverse hack? 

Either way thanks again for contribution.

**Comment by jlark** [comment]
Hi Glyn,
All good points, I’ll create a separate config and name it accordingly. I’m not affiliated with Victron but we use their products a lot as the produce the best off grid solar equipment in our opinion. 

VEDirect is a open protocol that they use to communicate between their products.  This is a mix between a reverse hack and proper implementation as full protocol is binary and this only deals with the ascii compontent of the protocol. 

Emonhub can now communicate with any victron product like their MPPT’s , small inverters, Battery monitors etc.


I’m not affiliated with victron we just happen to both love emon and victron : )


Alp Tilev

**Comment by jlark** [comment]
Done!

**Comment by glynhudson** [comment]
Great, any chance you could also remove the entry from the default emonhub.conf since I don't want to confuse users with too many configs. The `vedirect.emonhub.conf` could contain *just* the vedirect config example. That would be nice and clean. The vedirect.readme you have added is great, very well explained.

**Comment by jlark** [comment]
Ahh I thought i did well check.

Mobile typing




On Fri, Mar 4, 2016 at 9:20 AM -0800, "Glyn Hudson" <notifications@github.com> wrote:












Great, any chance you could also remove the entry from the default emonhub.conf since I don't want to confuse users with too many configs. The vedirect.emonhub.conf could contain just the vedirect config example. That would be nice and clean. The vedirect.readme you have added is great, very well explained.

**Comment by jlark** [comment]
OK, It looks like I had made a mistake in the config files. 

I removed everything else from the vedirect config to only show the example config and left the original emonhub.conf as is.

**Comment by glynhudson** [comment]
Marged, thanks a lot! Do you have a blog or a site I can link my users  to with more info regarding interfacing with Victron Energy products?

**Comment by jlark** [comment]
Hi Glyn,
I'm currently writing a blog post, I'll be posting it on my own blog as well as Victron's blog. I'll share the link once they are up.

Glad I can help : )

Alp

**Pull request merged**
