### PR TITLE
Python3 fixes

### PR DESCRIPTION
**Pull request by TrystanLea**
Reopened against new python3 master branch

### CODE REVIEW

**Comment by TrystanLea** [comment]
@bwduncan should I merge this?

**Comment by bwduncan** [comment]
Yes, please do! I've been running it happily for some months. If the existing systems can be upgraded painlessly, I see no reason not to continue.

In case it's not clear, this code won't run with python 2.

**Comment by glynhudson** [comment]
Can this be closed? Python 3 is now supported

**Comment by borpin** [comment]
@TrystanLea can we check and see if all this has actually been merged already and if so close this please.

**Comment by TrystanLea** [comment]
This has not been merged yet, they key is that its python3 only, I think we are probably safe to merge (and resolve conflicts now).. but I cant be sure?

**Comment by borpin** [comment]
I think it might need to be rebased as some of it must have gone into master.

**Comment by TrystanLea** [comment]
I've fixed the conflicts and pushed to a new branch, with pull request https://github.com/openenergymonitor/emonhub/pull/132

Testing briefly here looks like its all working fine. Are we safe to merge?

Both the latest image and the Oct19 image upgrade fine to python3 so these should work fine with these changes.

Older systems are running the emon-pi branch which has not been update now that we have master and stable branches. Merging this pull request will not affect these systems and updates are disabled anyway for these older systems.

I think we are safe to merge this, can anyone see any issues with that?

**Pull request merged**
