### PR TITLE
Addition of modbus TCP interfacer

### PR DESCRIPTION
**Pull request by cjthuys**
I have created a new class called EmonModbusTcpInterfacer. I have used this to retrieve data from my FRONIUS Solar inverter and display the results in emoncms.  

I hope I have created it in such fashion so as to enable it to talk to any modbustcp device. Provided of course then end user knows what registers to query and what data types those registers hold.

My end game is to be able to display power generated and power exported/imported from the grid and hopefully others will be able to take advantage of this code.

### CODE REVIEW

**Comment by glynhudson** [comment]
Wow, amazing nice work. Have you written some sort of blog or somwhere I can find more info about this? It would be great to have a guest blog on our site if you were keen? 

Is this an open protocol?

**Comment by cjthuys** [comment]
I don't have a blog or anything, I am not much of a writer.   Modbus is a protocol used heavily in industrial applications for controlling and monitoring equipment. Originally it was used over serial interfaces and now it has been encapsulated to run over tcp.  I have used pymodbus to do all the heavy lifting, it is a git project so there is more info there.

**Comment by glynhudson** [comment]
I have had to 'unmerge' these changes since I realised that all emonhub users will need to install `pymodbus` otherwise the application crashed and exists. How can we get around this? I don't want to force all emonhub users who are not using Modbus to install this library. Pleae could submitt another PR that makes modbus optional.

**Comment by alexandrecuer** [comment]
I've tried your work with an industrial master modbus SOFREL S500
It's working quite well.....
By the way, I am not very familiar to Python and I am trying to understand the architecture of EmonHub...the emonhub_coder.encode function is little endian, isn'it ?

**Comment by glynhudson** [comment]
Great! Good to hear. I believe so, @pb66 might be able to answer your question in more depth, he architected emonHub.

**Comment by pb66** [comment]
It is indeed little endian, defined [here](https://github.com/openenergymonitor/emonhub/blob/emon-pi/src/emonhub_coder.py#L36). The [python docs for the struct module](https://docs.python.org/2/library/struct.html) will possibly give better in-sight to emonhub's use of datacodes.

**Comment by Pukkahq** [comment]
Hi cjthuys,
I have tried your emon modbus interface with our inverter (Solax) I am unable to use register 40010 but with trial and error register 267 works.

with qModMaster I am able to query 40010 correctly. so I am now a little lost.
I have opened a forum thread at https://community.openenergymonitor.org/t/pymodbus/3708/3
or my email is GitHub@bpnl.co.uk 

Thanks
Paul

**Pull request merged**
