### PR TITLE
emonNOTIFY - remote visual monitoring device

### PR DESCRIPTION
**Pull request by stuartpittaway**
This commit adds the ability to send feed data over the RFM module in the emonPI device on a periodic basis.  

This is the core code for my emonNotify device based on the emonTX v2 PCB and a Nokia 5110 based display - further information and article on building this device is on its way.

Arduino code and 3d printing case is here 
https://github.com/stuartpittaway/emonNotify

### CODE REVIEW

**Comment by stuartpittaway** [comment]
I've merged the base emonhub into the PR without issues

**Comment by glynhudson** [comment]
Hi @stuartpittaway ,

Very sorry for the long delay in reviewing this! emonNotify sounds interesting but since not may users are currently using an emonnotify I am hesitant to merge all these changes into emonhub.

**Comment by stuartpittaway** [comment]
Sure fully understand the low usage angle for this

**Comment by pb66** [comment]
@stuartpittaway and @glynhudson this (and many other previous PR's/changes/developments) doesn't "fit" with how emonhub is structured and designed to work. Please take these comments as constructive, the last thing I want to do is dampen any efforts made in this direction, after all this type of development is what emonhub was designed for and even if there were no other users of emonNotify, you should be able to drop a file into the emonhub filesystem for it to work without needing to modify the existing source, as I guess now Stuart, you will miss out on some future updates to emonhub unless you manually merge them into your  own version.

Each interfacer is an interface with a specific device, the EmonHubJeeInterfacer is (supposed to be) the interface that interfaces with any JeeLib based rfm device **only**, even the modifications made to accommodate the emonPi mean the EmonHubJeeInterfacer is no longer that, it is now a poorly named emonpi interfacer and there is no generic jee interfacer any more.

This PR tries to squeeze 3 seperate interfacers into one, you should perhaps have an "emonNotify" interfacer to support the custom way your device works (unless it is 100% JeeLib compliant) that could inherit from the JeeInterfacer if you chose, in the same way the JeeInterfacer inherits from the serialinterfacer.

As for retrieving the data from emoncms, that should ideally be part of the emoncmshttpinterfacer, but you could just as easily (because that interfacer doesn't "fit" either) create a new "fetch only" emoncms interfacer.

Once you have the emoncms fetching interfacer collecting data from emoncms it could put that data to a "toRFM" channel which either the [[RFM2Pi]] interfacer or your brand new emonNotify interfacer are listening to, which in turn would transmit the data.

The current trend is to use the same single channel `pubchannels = ToEmonCMS,` for everything which undermines the whole design of emonhub and takes us back to the limitations of the OEM Gateway.

Prior to the emonpi variant of emonhub, the transmit side of things worked well within the JeeInterfacer, all you needed to do was open a channel and pass csv to it and it was transmitted. I do not know if that is still working but that's how it should (and previously did) work, eg for the emonGLCD.

No single interfacer should interface with more than one type of device or service and each channel should be task oriented, each interfacer can publish to multiple channels and subscribe to multiple channels.

I hope this helps with future development @stuartpittaway and reviewing future PR's @glynhudson.

**Comment by stuartpittaway** [comment]
Thanks for the comments @pb66 

The emonHub is 100% compatible with the EmonHubJeeInterfacer  however putting that aside, I agree that the code in this PR is more of a fudge than a cleanly seperated interface.

The root problems that I found when building this code were:

1. Lack of architecture diagrams or building blocks - is the emonHUB code goals/design methods documented anywhere?

2. Lack of example code - there isn't any existing code (apart from a 1 liner for emonGLCD that sets the time) that appeared to read feed data and push out the RFM module

3. I'm not sure if the emonhub software is strategically part of the long term OEM solution (see point 4!) as there is some move to using MQTT and Node Red which could easily cater for the input/output processes that emonCMS needs.

4. The whole OEM eco system really needs a documented future direction and goal (strategy) - whats the target platform to work with/aim for?  The emonPI is a great base, but does the project team want to drop RFM based comms in favour of direct wifi, or MQTT, node red etc etc ?

None of the above are criticisms of the project or individuals work - open source projects take a long time to mature and documentation is normally the last thing anyone wants to do (including me!), 

I just feel that folks are going to waste time and money building or developing software which won't get the long term support or integration into core for others to benefit from.

**Comment by pb66** [comment]
Hi @stuartpittaway 

Sorry I haven't replied sooner, I understand or agree with all your points and hopefully your comments will help towards finding some solutions or at least some clarity.

**Comment by TrystanLea** [comment]
@stuartpittaway were working on some of the issues you raised, I took emonhub off in different direction to what @pb66 had in mind and am now trying to resolve some of the issues I ended up creating in the emon-pi variant of emonhub and discussing with Paul each detail so that we can hopefully get to a point where the variants can merge again. Then hopefully the result of that can be a clearer guide for prospective emonhub developers as to how to build interfacers etc.

**Comment by stuartpittaway** [comment]
@TrystanLea thats good to know and thanks for taking the time to add a comment to this thread.

**Comment by TrystanLea** [comment]
Thanks Stuart, I've been doing a fair bit of work in the emonhub_buffer branch, I wonder if you might have a chance to test it to see if you see any issues with the BMW interfacer?
https://github.com/openenergymonitor/emonhub/tree/emonhub_buffer

The main thing the branch fixes is the buffering for the emoncms http interfacer, reverting it back to how it was done in @pb66's experimental branch. There are also a number of changes to the way the settings are set which brings it back in line with Pauls experimental branch.

**Comment by stuartpittaway** [comment]
@TrystanLea  happy to try out - I can never remember the command line for GIT to swap branches - can you help?

**Comment by pb66** [comment]
once you've updated the repo by pulling in any changes you should be able to switch branches with `checkout` eg
```
git pull
git checkout <branch_name>
```

**Comment by TrystanLea** [comment]
> The whole OEM eco system really needs a documented future direction and goal (strategy) - whats the target platform to work with/aim for? The emonPI is a great base, but does the project team want to drop RFM based comms in favour of direct wifi, or MQTT, node red etc etc ?

We've published a post outlining OEM goals and sub projects more generally https://community.openenergymonitor.org/t/openenergymonitor-goals-2018-2019/6576/3

We have no intention of dropping RFM based comms, its still the cheapest way of getting data from an emontx or emonth. I can see the emontx being used increasingly with an esp module & MQTT, or perhaps @pb66's pi zero idea? and we've been discussing passing that data via emonhub rather than bypassing straight to emoncms. I think its got to be a multi platform approach, with technology moving fast all the time, the ground keeps moving.

**Pull request closed without merging**
