### PR TITLE
Adding fixes for python3 SMA support

### PR DESCRIPTION
**Pull request by k-quigley**
A number of issues flagged under #102 

This PR implements changes required to get SMA bluetooth support working again under python3

### CODE REVIEW

**Comment by TrystanLea** [comment]
Thanks @k-quigley looks great, I cant test here other than checking that emonhub continues to run with standard config which looks fine. Great to have this updated interfacer

**Comment by bwduncan** [comment]
Hi,

Thanks for checking and fixing my work. It was never meant to be perfect!

I've spotted a couple of issues with your code, though. There's one bug where you never import os so that bluetooth restart would just fail. That's easily fixed and there are nicer ways of achieving the same thing. I hope you agree.

noBluetooth_reported is a local variable which is not initialised before being used. This would also just raise an exception. I moved it to an object variable.

It looks like you've reverted part of my changes to be much more verbose. There's a comment with my code, then the same thing over two lines, but that's not necessary:

```python
In [1]: a = '0123456789'                                                                                                                                                  

In [2]: a[0:-3]                                                                                                                                                           
Out[2]: '0123456'

In [3]: a[0:len(a)-3]                                                                                                                                                     
Out[3]: '0123456'
```

I just reverted that change. If it breaks things, please educate me as to why!

And the same thing in another place:

```python
In [26]: byteone, bytetwo = 3, 4                                                                                                                                          

In [27]: b = bytearray()                                                                                                                                                  

In [28]: b.append(byteone)                                                                                                                                                

In [29]: b.append(bytetwo)                                                                                                                                                

In [30]: b == bytearray([byteone, bytetwo])                                                                                                                               
Out[30]: True
```

I reverted that change, too.

I removed what looked like no-longer-needed debugging statements. If they are really useful then use `self._log.debug()`

In case you used something like `git commit -a`, you might find it useful to review your changes before committing with `git add -p`, then `git commit` to only commit the lines you picked. I find it useful, anyway!

Am I correct in assuming that you actually have one of these devices? If so, it would be a nice exercise to clean up some of the FIXME and TODO comments in this code. I'd be happy to help!

I made a new pull request for this #111 

Bruce

**Comment by k-quigley** [comment]
Hi,

I’ve been working on those fixes in parallel.  We found similar issues – mostly caused by my bad “merge” of our improvements for the BT handling.  We find that the RPI Bluetooth adapter seems to not work reliably with the SMA inverter over the long term; and the error checking is not functional.    I’m verifying some fixes in that area of the code and over the next couple of days I’ll introduce your changes too & test them.

Regards


Kevin

**Comment by k-quigley** [comment]
Good evening,

On the subject of reverting the following change:

In [2]: a[0:-3]

Out[2]: '0123456'



In [3]: a[0:len(a)-3]

Out[3]: '0123456'

The payload in the data – causes some “errors” in certain cases with your code.

e.g. I added the debugging:
        print ("ArrayLength = " + str(len(self.UnescapedArray[startbyte:-skipendbytes])))
        print ("ArrayLength = " + str(len(self.UnescapedArray[startbyte:l])))
        print (self.UnescapedArray[startbyte:-skipendbytes])
        print (self.UnescapedArray[startbyte:l])

Most times the code works; but here is an example when the length check and content of return variable,  is zero:
ArrayLength = 0
ArrayLength = 89
bytearray(b'')
bytearray(b"\xff\x03`e\'\x90\x08\x00\xaa\xbb\xcc\xdd\x00\xa0N\x00]\xa21}\x00\x00\x00\x00\x00\x00\x03\x81\x01\x02\x00X\x00\x00\x00\x00\x02\x00\x00\x00\x01\x1e\x82\x10\xd7{\xf1^SN: 2100404829\x00\x00\xe6\x00\x00\x00\xe6\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x1f\x82\x08\xd7{\xf1^A")

I can’t see immediately – why this is the case…  All I know is that the “verbose” code works, whereas the new code doesn’t.  We’ll have to revert that – unless you can immediately see why it doesn’t work.


The Bluetooth reset code – is looking much cleaner.. but to make this work – we need so extend the sudoers file:
pi@emonpi:/etc/sudoers.d $ sudo cat emonhub-sudoers
www-data ALL=(ALL) NOPASSWD:/bin/systemctl restart emonhub
emonhub ALL=(ALL) NOPASSWD:/bin/systemctl restart bluetooth
emonhub ALL=(ALL) NOPASSWD:/bin/hciconfig hci0 reset

I’ll leave this to run in my environment for a couple more days – then look to merge/patch your code too.


Hope this helps.


Regards


Kevin

**Comment by bwduncan** [comment]
Hi Kevin,

That's fascinating! I see the bug now. It happens if the payload isn't escaped. I'm surprised that actually happens. I would expect that to come from a corrupted/truncated packet. Maybe it gets dropped later, who knows. If the last byte isn't `0x7e`, `skipendbytes` is zero, and negative zero being equal to positive zero, I'm asking for the array to finish at the zeroth element. Python obliges.

There's a slightly odd syntax which will correct the problem, where the variable is initialised at the start of the function, set it to `None` instead of `0`. That will fix the bug but we should be asking ourselves whether this data is even valid.

Re the sudoers bits: The hciconfig line isn't required unless I'm missing some other piece of the puzzle. The install/upgrade scripts scare me quite a lot, but there are much smarter people here who will be able to put the right things in there to get that updated at the same time the code is deployed.

Thanks!
Bruce

**Comment by k-quigley** [comment]
Hi,

I think the last byte is not 0x7e – when there is a multi-packet transmission.  This happens quite a bit in the data exchange….

I’ll try the “None” initialization and see how it goes.

The HCI config – is today’s discovery… there are cases where BT gets really quite stuck; and the simple restart doesn’t fix it.   This part -> I’ll soak test over the next few days.

Regards


Kevin

**Pull request merged**
