### PR TITLE
Goodwe 5ket

### PR DESCRIPTION
**Pull request by ziporah**
This is the PR as suggested by Bruce, to make the tracking easier

### CODE REVIEW

**Comment by ziporah** [comment]
If you make a pull request it makes it easy for people to review and comment.

It looks like this commit Change deprecated function · openenergymonitor/emonhub@b6ba086 · GitHub adds src/emonhub.conf which seems like a mistake.

The default value for ip should be None, not False. The superclass __init__ already does self._settings.update(self._defaults) so it doesn’t need to be done here (I appreciate this is done in other interfacers, I will aim to fix that).

Can we just call it goodwe instead of goodwelibrary? The fact that it appears in an import statement already implies it’s a library. Also renaming the class in the import statement (using as) confused me for a while. Can we just use its actual name?

I am not sure what catching the asyncio.CancelledError exception does, apart from maybe hiding bugs. If the task is cancelled, data certainly won’t be valid. If there is a reason why the task might be cancelled, I would say we should just return there. However I would strongly argue that we should not catch any exceptions here, since we can’t do anything useful about it. The thread will be restarted when exceptions are raised and we get nice verbose logs.

It looks like the big list of sensors in the for loop is just a copy of ET.__sensors. Could we just use that directly?

**Comment by ziporah** [comment]
Renamed GoodweLibrary to Goodwe and changed False to None

**Comment by ziporah** [comment]
The reason I don't use the list in ET_.sensors is due to it being extremely large. I wouldn't want all this data injected in emoncms. There are also unknown values in the full list. They are yet to be identified and debugged to confirm what they really present. I want to extend the interface even more, that you can select which values you really want. I just didn't come around to it yet and was wondering if anyone would really use it this way. @bwduncan 
```json
{'vpv1': 0.0, 'ipv1': 0.0, 'ppv1': 0, 'vpv2': 0.0, 'ipv2': 0.0, 'ppv2': 0, 'ppv': 0, 
'xx38': 0, 'xx40': 0, 'vgrid': 222.6, 'igrid': 0.9, 'fgrid': 50.0, 'pgrid': 8, 
'vgrid2': 222.0, 'igrid2': 0.9, 'fgrid2': 50.01, 'pgrid2': 13, 
'vgrid3': 229.1, 'igrid3': 1.0, 'fgrid3': 50.02, 'pgrid3': 11, 
'xx72': 1, 'total_inverter_power': 28, 'active_power': -795, 
'grid_in_out': 2, 'grid_in_out_label': 'Importing', 'xx82': 0, 'xx84': 0, 'xx86': 0, 
'backup_v1': 223.0, 'backup_i1': 0.1, 'backup_f1': 50.0, 'xx96': 1, 'backup_p1': 6, 
'backup_v2': 221.7, 'backup_i2': 0.1, 'backup_f2': 50.02, 'xx108': 1, 'backup_p2': 5, 
'backup_v3': 230.1, 'backup_i3': 0.2, 'backup_f3': 50.02, 'xx120': 1, 'backup_p3': 6, 
'load_p1': 638, 'load_p2': 133, 'load_p3': 39, 'load_ptotal': 810, 'backup_ptotal': 17, 'pload': 807, 'xx146': 1, 
'temperature2': 32.9, 'xx150': 0, 'temperature': 28.2, 'xx154': 0, 'xx156': 6543, 'xx158': 3245, 
'vbattery1': 244.4, 'ibattery1': 0.0, 'pbattery1': 0, 'battery_mode': 1, 'battery_mode_label': 'Standby', 
'xx170': 0, 'safety_country': 6, 'safety_country_label': 'Belguim', 'work_mode': 1, 'work_mode_label': 'Normal (On-Grid)',
'xx176': 0, 'error_codes': 0, 'e_total': 32.5, 'e_day': 11.0, 'xx190': 0, 's_total': 46.6, 'h_total': 122, 
'xx198': 130, 's_day': 0.0, 'diagnose_result': 50856070, 'house_consumption': 795, 
'battery_bms': 255, 'battery_index': 311, 'battery_temperature': 21.0, 'battery_charge_limit': 40, 
'battery_discharge_limit': 12, 'battery_status': 0, 'battery_soc': 10, 'battery_soh': 100, 'battery_warning': 0, 
'xxx0': 1, 'xxx2': 30, 'xxx4': 10, 'xxx6': 273, 'xxx8': 1, 'xxx10': -640, 'xxx12': -124, 'xxx14': -35, 'xxx16': -799, 'xxx18': 688, 'xxx20': -891, 'xxx22': -347, 'xxx24': -204, 'xxx26': -636, 'xxx28': 5001, 'xxx30': 17547, 'xxx32': 6656}
```

**Comment by bwduncan** [comment]
Hey,

That's all looking really good.

I think `import json` is not needed.

I'm not sure I understand about the sensor list, though. Surely it is best to just pass everything through. The "Jee" interfacer, for example, doesn't give you a choice. If you only have one temperature sensor, you get 5 zeros for the other, missing, sensors! Anyway I think something like this would be much simpler

```python
for key in Goodwe_inverter.ET.__sensors:
    name = key.name
    if name not in data:
        self._log.warning("etc")
        return
    names.append(name)
    values.append(data[name])
```

Just a thought. Not tested, comes with full money-back guarantee.

Bruce

**Comment by ziporah** [comment]
Returning all numeric fields now that are detected and filled in by the readout. It's quite a list now.
I'll figure out which fields are to be used for correctly monitor the battery status in the dashboard. I believe all the necessary data is exported by default. If I can get them all out, I'll also add this in the readme of the interface

**Comment by ziporah** [comment]
still figuring out what fields best to use to get a correct view of the invertor and battery. My second solar system is giving me additional troubles, so I'll first have to make sure I'm measuring this correct. I'll update asap, still waiting on some hardware replacement components for the voltage measurement of my third phase

**Review by bwduncan — APPROVED** [review]

**Comment by ziporah** [comment]
I believe it is safe to merge this branch.
I'll cleanup the names and set the correct ones for the additional entries I've found in a new PR.
The system is finally stable and my readings are correct now. It was quite challenging recalibrating the entire system.

**Comment by TrystanLea** [comment]
This looks great @ziporah, thanks for contributing!

**Pull request merged**
