### PR TITLE
PR for BMW and SMA Solar inputs into emonHub

### PR DESCRIPTION
**Pull request by stuartpittaway**
Please review my changes for a BMW API input and a SMA Solar inverter input for emonhub,

### CODE REVIEW

**Comment by glynhudson** [comment]
Wow, this is great. Very impressive PR. I wish I had an i3 and SMA to test! All the changes are well documented and in the correct places. 

Just tested the PR updating from the master branch, it seems I get a BT is not defined error:

```
pi@emonpi(rw):~/emonhub$ src/emonhub.py 
Traceback (most recent call last):
  File "src/emonhub.py", line 48, in <module>
    if bluetooth:
NameError: name 'bluetooth' is not defined
````

**Comment by stuartpittaway** [comment]
Its always the little things that catch the code out!

bluetooth should be "bluetooth_found"


I've fixed that in github - do I need to do another PR ?

**Comment by Steve720** [comment]
Comment re maintainability: the recognised values from the inverter are nicely structured in spotvaluelist in smalibrary/SMASolar_library.py, but the same keys (e.g. 0x4640) are hard-coded in the cargo builder loop in interfacers/EmonHubSMASolarInterfacer.py. Better to have "for i in spotvaluelist" at this loop.

**Comment by glynhudson** [comment]
Nice, thanks. No you don't need to create a new PR. Any changes you push to your branch will get automatically included in this PR. I have re-opened it.

Just tested and backwards compatibility seems to be maintained. I've merged. Thanks a lot 👍 

If you have not done so already, would you mind posting about your changes on our community forum to let everyone know.

**Pull request merged**
