### PR TITLE
Update documentation and MQTT interfacer to send JSON

### PR DESCRIPTION
**Pull request by borpin**
Issue #100 

1. Update MQTT interfacer to send single, timestamped JSON data
2. Update Documentation and lint MarkDown
3. Add pub / sub channel information - **please check for accuracy**.
3. Add serial interfacer to documentation.
4. Add JSON settings to emonhub.conf (disabled by default).

### CODE REVIEW

**Comment by borpin** [comment]
This repository really needs a version file.

**Comment by TrystanLea** [comment]
Thanks @borpin is it possible to remove the indentation changes to the conf files to a separate pull request? At the moment the emonpi update process compares the local copy to the default in the conf file and updates if there is a change so Im keen to at least keep the emonpi.emonhub.conf file the same for now.

**Comment by borpin** [comment]
@TrystanLea, I have done it for the nodes, but the left the rest of the file as I added in some new settings options to the MQTT section.

Do you need those removed as well?

**Comment by borpin** [comment]
@TrystanLea - is this OK now?

**Comment by TrystanLea** [comment]
Sorry for the delay in merging this, its now in master.

**Pull request merged**
