### PR TITLE
Resolve Issues with modbus interfacer and pymodbus

### PR DESCRIPTION
**Pull request by cjthuys**
Removed py-modbus check from emonhub.py and added to modbus interfacer
resolved issues with import of EmonModbusTcpInterfacer in EmonFroniusModbusTcpInterfacer
moved fronius and modbus interfacers out of tmp directory. enabled fronius and modbus interfacers in __init__.py script

### CODE REVIEW

**Comment by alexandrecuer** [comment]
Hello

have you tested this with a version of pymodbus > 1.4.0 ?

To make it to work properly, I had to change line 108 of EmonmodbusTcpInterfacer.py from
`decoder = BinaryPayloadDecoder.fromRegisters(self.rVal.registers, endian=Endian.Big)`
to 
`
decoder = BinaryPayloadDecoder.fromRegisters(self.rVal.registers, byteorder=Endian.Big, wordorder=Endian.Big)
`

cf the pull request submitted some times ago...
[https://github.com/openenergymonitor/emonhub/pull/52/files](https://github.com/openenergymonitor/emonhub/pull/52/files)

Alex

**Comment by glynhudson** [comment]
Hi guys, very sorry for the very slow reply. I don't know how I missed this. I just got prompted to search for this by a forum member reporting a issue: https://community.openenergymonitor.org/t/monitor-fronius-primo-5/9437

I've just tested this PR and I get an error `ImportError: No module named pymodbus.constants`. I'm running standard emonSD-30Oct18. This does not have pymodbus install by default. I will add pymodbus to a future emonPi update. However, would it be possible to add a check to see if pymodbus is not installed since many users of emonhub will not be used modbus but still require emonhub to run. This error fully crashed emonhub. 

Please include @alexandrecuer changes if required, I see the current version is `pymodbus-2.1.0`

**Comment by alexandrecuer** [comment]
@glynhudson : my PR should fix the problems encountered (ImportError, crash if pymodbus not installed, etc, etc)...

It has been tested on various modbus and mbus devices and it is working fine.....

Anyway, I don't have a fronius device so I cannot test the fronius part...anyway, the EmonModbusTcpInterfacer is enough to work with modbus devices...

I use to install pymodbus with git rather than using pip..Anyway, there should be no difference

Alex

**Comment by glynhudson** [comment]
Thanks @alexandrecuer , I've tested and merged you PR. 

I will close this PR since it's a duplicate of https://github.com/openenergymonitor/emonhub/pull/52

**Pull request closed without merging**
