### PR TITLE
Thread exception reporting, thread restarting, restart counting...

### PR DESCRIPTION
**Pull request by beaylott**
Based on discussion:
https://community.openenergymonitor.org/t/emonhub-minor-code-cleanup-enhancements-and-python3-support/4538/7

This implements thread restarting, restart counting, and logging of tracebacks within threads.

### CODE REVIEW

**Comment by TrystanLea** [comment]
Thanks @beaylott, are you working with @tim-seoss on this? I will try and take a look over the next few days

**Comment by beaylott** [comment]
@TrystanLea I did read the discussion thread started by @tim-seoss about his code changes. I focused here on catching exceptions in threads and one simple way of restarting them when they fail which seems to work. It is mainly based on what @pb66 was suggesting there and addresses problems I have had with emonhub threads dying.

**Comment by tim-seoss** [comment]
Thanks @beaylott I should be able to take a look towards the end of the week, busy before then.  I have just had a quick skim and a minor nit-pick is that it might be good to split out the whitespace / formatting fixes into a separate commit?  Up to the maintainers tho' obviously!

I think it'd be great to have some sort of automatic submission of backtraces with something like https://github.com/abrt (maybe something lighter than that?).  Probably best to move discussion of that to the forum...

**Comment by beaylott** [comment]
Sorry about the whitespace, my IDE does that automatically.

**Comment by beaylott** [comment]
Any one had a look at this yet? Would be good to get your thoughts on the proposed solution.

**Comment by TrystanLea** [comment]
Very nice, that worked well:

    2017-08-05 08:01:27,542 DEBUG    RFM2Pi     7 Sent to channel(end)' : ToEmonCMS
    2017-08-05 08:01:27,758 WARNING  MainThread MQTT thread is dead.
    2017-08-05 08:01:27,759 WARNING  MainThread Attempting to restart thread MQTT (thread has been restarted 0 times...
    2017-08-05 08:01:27,760 INFO     MainThread Setting RFM2Pi quiet: 0 (0q)
    2017-08-05 08:01:27,846 DEBUG    RFM2Pi     Discarding RX frame 'unreliable content'? 20 98 30 80 110 49 154 85 177 16 78 113 118 165 96 153 32 218 96 22 169 (-78)
    2017-08-05 08:01:27,947 DEBUG    RFM2Pi     acknowledged command: > 0q
    2017-08-05 08:01:28,049 DEBUG    RFM2Pi     device settings updated: E i5 g210 @ 433 MHz
    2017-08-05 08:01:28,152 DEBUG    RFM2Pi     Discarding RX frame 'unreliable content'? 24 192 167 38 83 207 236 229 55 218 7 63 134 40 87 72 213 217 8 71 10 (-91)
    2017-08-05 08:01:28,457 DEBUG

**Comment by TrystanLea** [comment]
I've merged your branch into my 'native_message_queue' branch which fixed some other threading issues. I've combined the result into a branch called emon-pi-develop which is ready for testing here: https://github.com/openenergymonitor/emonhub/pull/38

Im going to document the native message queue implementation next

**Comment by beaylott** [comment]
Ok I will go over to that .

**Pull request closed without merging**
